uptake:
  treated_fraction: 0.85
  dx_to_1l_delay_months: 1   # ~28 days is a common median in US data

attrition:
  p_reach_2l: 0.70
  p_reach_3l_given_2l: 0.70  # attrition exists; tune in calibration

durations_months_median:
  1l: 24       # TTNT/TNTD often ~17–24+ months depending on era/regimen
  2l: 16       # TTNT ~16.6 months reported in real-world cohorts
  3l_plus: 6   # later-line TTNT often ~5–6 months in refractory settings

mortality:
  monthly_death_hazard_1l: 0.003
  monthly_death_hazard_2l: 0.006
  monthly_death_hazard_3l_plus: 0.015

# Added during Audit
uptake_definitions:
  fraction_transplant_eligible: 0.40 # Standard US approximation (~30-50% depending on age cutoff)

attrition_definitions:
  p_reach_4l_given_3l: 0.50 # Assumption; attrition typically high in later lines
